### ISSUE TITLE
Json/Term Serializer

### ISSUE THREAD

**Issue by henry-hz** [slashdotdash/eventstore#24]
Hi, I tried to use the Json serializer, but the data in postgre is still as BYTEA [binary], and I would like to have it stored in JSON. 

Also trying to use  config :serializer: EventStore.TermSerializer, but the test runs with aprox 6 errors.

**Comment by henry-hz** [comment]
Solved, too much command line,  using pgadmin-III instead, we could see the JSON data there, thanks anyway.

**Comment by slashdotdash** [comment]
There's an example SQL statement to view the event data & metadata in [scripts/events.sql](https://github.com/slashdotdash/eventstore/blob/master/scripts/events.sql) if you want to view the raw data.

```sql
select
	event_id,
	stream_id,
	stream_version,
	event_type,
	correlation_id,
	convert_from(data, current_setting('server_encoding')) as data,
	convert_from(metadata, current_setting('server_encoding')) as metadata,
	created_at
from events
order by event_id;
```
