### ISSUE TITLE
Doc: what is a stream version number?

### ISSUE THREAD

**Issue by boxxxie** [slashdotdash/eventstore#28]
i looked in the code a bit for docs, and i see version number documented a little bit, but the concept is not obvious, and i still don't understand it or how to use it. i only see it being set to 0 in examples.

**Comment by Papipo** [comment]
It's for optimistic locking and anyway you shouldn't worry about it, it's handled automatically.

**Comment by slashdotdash** [comment]
Stream version is the expected version of the stream when appending events. It's used for optimistic concurrency to guarantee that you haven't missed an event written by another process.

The expected version is *always* 0 for a new stream.

```elixir
:ok = EventStore.append_to_stream(stream_uuid, 0, [%EventStore.EventData{..}])
```

Appending another event to the same stream would expect the version to be 1.

```elixir
:ok = EventStore.append_to_stream(stream_uuid, 1, [%EventStore.EventData{..}])
```

Attempting to append another event with an incorrect stream version returns an error.

```elixir
{:error, :wrong_expected_version} = EventStore.append_to_stream(stream_uuid, 1, [%EventStore.EventData{..}])
```

**Comment by boxxxie** [comment]
"Stream version is the expected version of the stream when appending events. It's used for optimistic concurrency to guarantee that you haven't missed an event written by another process.

The expected version is always 0 for a new stream." 

this sounds like it's right out of the docs. this doesn't really explain to me the purpose of a version.

"It's for optimistic locking and anyway you shouldn't worry about it, it's handled automatically."

from the documentation it isn't obvious that this is the case. it looks like from the docs i need to know about this and understand it.

is the version the index in the stream of an event?

**Comment by Papipo** [comment]
"**guarantee that you haven't missed an event written by another process**" that's quite explanatory IMO. Aggregates in DDD process events sequentially, so only one process should be writing to a given stream. Stream versions allow for optimistic locking if for any reason two processes try to write the same version.

It's not true that it's handled automatically, sorry. That would be if you were using [Commanded](https://github.com/slashdotdash/commanded).

**Comment by boxxxie** [comment]
ok, so this is a low level thing...
how would i get around the issue here? do i have to query the API to see what the last event # was? or do i have to keep track of that myself?

**Comment by boxxxie** [comment]
actually, after reading the benchmark code, i think that the stream ID is actually what may be confusing me.
i was under the impression that the stream ID was something similar to kafka topic names. but when i see the benchmark using a new ID per event dump, this is completely different. is this correct?

would the use-case for version be for when i know the order of events, but they are all async and i want to dump the in the stream when each finishes, and not wait for them all to finish when they are put in the stream?

sorry if i'm being annoying, i'm trying to understand the use-cases for the inputs to this function.

maybe this lib is very low level, but i feel that i can't use the higher level libraray without understanding this one first and getting it running on my project.

**Comment by slashdotdash** [comment]
### 1. Creating a new stream

Expected version is always 0.

### 2. Appending to an existing stream

You would have read the events first (e.g. to rebuild you're aggregate's current state). 

So you know the expected version as it is the number of events read.

```elixir
{:ok, events} = EventStore.read_stream_forward(stream_uuid)

expected_version = length(events)

:ok = EventStore.append_to_stream(stream_uuid, expected_version, [%EventStore.EventData{..}])
```

**Comment by slashdotdash** [comment]
Greg Young wrote a detailed [CQRS document](https://cqrs.files.wordpress.com/2010/11/cqrs_documents.pdf) that includes a section "Building an Event Storage". 

Worth a read for the background on the use case for an event store.

**Comment by boxxxie** [comment]
I don't believe the way eventstore is implemented here is the only way, i'm trying to understand this code base.

anyway, i got the stream ID and maybe stream_version concepts down. i really like the stream_id, it helps a lot when i'm writing tests so i can scope the log to only the code that executed. very cool. but i can see cases when i will not know the streamversion, or they will conflict depending on code-paths taken.

also, i found another bug, related to not implementing access behaviour. i'll make a new issue for that, with an example of how to do so.

**Comment by boxxxie** [comment]
wow, it seems like a lot of work to figure out the stream-version.
i'm thinkink about this in terms of a test perspective, i may have a few functions execute in a test that produce events, and i can figure out the stream-version without much issue (in my test, i am creating a stream for the whole test).

but, lets say i have 2 functions, one will put 2 events on the stream, one will put 1 event on the stream after the first function finishes. so my second function will have a stream-version of 2, but sometimes it wont (like when it make's it's own stream ID outside of a test context).

or, maybe i should never have these functions creating stream_IDs, and just use a shared context always... or am i doing this completely wrong? do you have suggestions for how i should do this?

**Comment by boxxxie** [comment]
"Providing the expected version ensures no events were persisted by any other process between reading from, and then appending new events to the stream."
what do you mean by this exactly?
when i append to a stream, do the events not get persisted? or if they don't, how would i persist them?
also, if events get persisted, then they drop from the stream?

**Comment by slashdotdash** [comment]
One approach is to create an Elixir process per logical stream. Use stream UUID and version as the process state. Then you can record the stream version after reading (number of read events), or on write (current expected version + number of events to append). Using a process also serializes reads/writes. So you won't have an issue with concurrent access.

Have a look through the existing [test suite](https://github.com/slashdotdash/eventstore/tree/master/test) to see an example of usage.

**Comment by boxxxie** [comment]
i like the idea of a process per ID, but i'm going to avoid that until the next iteration of my code. my code is already running in a process. i'm just going to have a stream_context passed around everywhere that i use a stream ID.
i'm looking at the tests, and reading the paper.

**Comment by Papipo** [comment]
In a DDD context the stream_id = aggregate_id. They are the same thing. And in that same context you want one process per aggregate/stream.

**Comment by boxxxie** [comment]
cool, that's what i've done (i set a stream ID when i get an API request). for testing it makes things really nice.

still on stream_version. does it increment on event or event_batch? like, if i give it 10 events in the append_to_stream function, will the next version be 10 higher, or 1 higher?

**Comment by boxxxie** [comment]
https://github.com/slashdotdash/eventstore/blob/master/test/streams/stream_test.exs#L106
this makes it look like stream_version is actually the number of discrete events given to the stream

**Comment by slashdotdash** [comment]
Stream version increments per event.

**Comment by karmajunkie** [comment]
How would one commit events without using optimistic concurrency (i.e. expectedVersion or the like)? OC is great when you need it but when you don't it prevents a write without reading the current state of a stream, which is unnecessary for many projection designs.

**Comment by slashdotdash** [comment]
@karmajunkie optimistic concurrency checking is mandatory on writes. I've just added a proposal to allow this to be optional (#31).
