### ISSUE TITLE
EventStore.RecordedEvent does not implement the Access behaviour

### ISSUE THREAD

**Issue by boxxxie** [slashdotdash/eventstore#30]
`(EventStore.RecordedEvent does not implement the Access behaviour)`
when i use get_in to access fields.

https://github.com/planswell/kitchen-sink/blob/master/lib/kitchen_sink/struct_access.ex

here is an example of how to implement this...

would you be interested in a PR?

**Comment by slashdotdash** [comment]
@boxxxie Does that require just adding `fetch/2` and `get_and_update/3` functions? Then happy to take a pull request to add.

**Comment by boxxxie** [comment]
yes, it does.
ok. i'll give you a PR soon.

**Comment by slashdotdash** [comment]
Fixed by #37.
