### ISSUE TITLE
Provide an example of a projection in the README

### ISSUE THREAD

**Issue by nicholasjhenry** [slashdotdash/eventstore#33]
In the meantime, I would be grateful for an example posted to this issue. Thank you!

**Comment by slashdotdash** [comment]
@nicholasjhenry I've used Ecto to create the read-side projections in an application. 

It uses the [`Commanded.Event.Handler`](https://github.com/slashdotdash/commanded/blob/1c75c2ce9f4e56adc2fc4f948b9f157c250b5746/lib/commanded/event/handler.ex) module from my [Commanded](https://github.com/slashdotdash/commanded) CQRS library to handle the event acknowledgment.

- [Building projections with Ecto using Commanded event handlers](https://gist.github.com/slashdotdash/1287f0c0735b49cca8afcc1b67665b42).

I'm planning to extract this out into it's own library and GitHub repository. Using Ecto to support multiple relational databases. I had planned to make it depend upon Commanded, but there's no reason why it couldn't just extend the eventstore. I want to keep the event handlers as generic as possible. 

Would providing such a library help you out?

**Comment by nicholasjhenry** [comment]
Thank you so much, @slashdotdash. This is great and much appreciated.

> Would providing such a library help you out?

Absolutely. This felt like a missing piece of the puzzle and would complete your libraries Commanded/EventStore. It would definitely help folks get started on using this approach for the first time (like me). I like your EventStore library as it uses a backend that I'm familiar with and so simple to get started with. Projections were the missing piece -- look forward to trying out your examples today. Thank you!

**Comment by nicholasjhenry** [comment]
Tried this out this morning, worked great. Thanks again 👍

**Comment by slashdotdash** [comment]
I've created [Commanded Ecto projections](https://github.com/slashdotdash/commanded-ecto-projections) for building your read-model.

Here's an example of using the `Commanded.Projections.Ecto` macro:

```elixir
defmodule MyApp.ExampleProjector do
  use Commanded.Projections.Ecto, name: "example_projection"

  project %AnEvent{name: name}, _metadata do
    Ecto.Multi.insert(multi, :example_projection, %ExampleProjection{name: name})
  end

  project %AnotherEvent{name: name} do
    Ecto.Multi.insert(multi, :example_projection, %ExampleProjection{name: name})
  end
end
```
