### ISSUE TITLE
Investigate using `Postgrex.stream` to append events to storage

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/eventstore#35]
It's possible to stream data to PostgreSQL from STDIN by using [Postgrex.stream/4](https://hexdocs.pm/postgrex/Postgrex.html#stream/4).

```elixir
Postgrex.transaction(pid, fn(conn) ->
  stream = Postgrex.stream(conn, "COPY events FROM STDIN", [])
  Enum.into(events, stream)
end)
```

Investigate using this and benchmark its affect on performance.

**Comment by slashdotdash** [comment]
[Here's an example](https://github.com/rawcodehq/fast_io_with_postgrex) of using this approach where the import time was reduced from 4 minutes to 1.7 seconds.

**Comment by slashdotdash** [comment]
I've implemented streaming events into PostgreSQL using `COPY FROM STDIN` in binary format. 

- [EventStore.Storage.Appender](https://github.com/slashdotdash/eventstore/blob/e2ac45d0c99fd58d89f8643b1795a4bd39f0187a/lib/event_store/storage/appender.ex)

The append event benchmarks, using 100 events, shows that there is a significant negative performance impact. It's almost twice as slow as the existing multi-row insert SQL statement. I imagine that the performance be better for very large numbers of rows to insert (e.g. batch import). But the use case for appending events to a stream is typically only a few at a time.

**Comment by pcarvsilva** [comment]
@slashdotdash,
Any chance of reviving this idea ?
It would be great if when I send a large batch of events a guard clause switches the implementation to this one.
I`ve been having some performance issues on seeding a large database from scratch
