### ISSUE TITLE
Allow `event_store.create` to initialize existing databases

### ISSUE THREAD

**Issue by rranelli** [slashdotdash/eventstore#41]
I've started evaluating event_store for production usage over here.

One of the things I've noticed is that the `event_store.create` mix task refuses to run the initialization commands on an existing database. 

We don't want to create another database solely for the event store, so we ended up running `Storage.Initializer.run!/1` manually ~ It would be convenient to have an option to run those even if the db is already created.

Would this be an interesting addition? I would have a go at it if that's the case.

**Comment by slashdotdash** [comment]
Yes, I'm happy to accept a pull request to add an additional mix task to handle this scenario.

**Comment by rranelli** [comment]
Alright ~ 
I'll get a proposal up soon enough :)

Thanks

**Comment by dustinsmith1024** [comment]
My issue was similar but not exactly the same.  I don't normally have Postgres installed locally, since I use a docker instance.  It'd be nice to just make the database manually then have the command initialize if already created.  Not a big deal, just documenting. I installed Postgres to get around it.

**Comment by slashdotdash** [comment]
@dustinsmith1024 Would you be interested in contributing a pull request to make this change? 

It should be a small change:

1. Copy the existing [mix/tasks/event_store.create.ex](https://github.com/slashdotdash/eventstore/blob/master/lib/mix/tasks/event_store.create.ex) module to e.g. `event_store.init.ex`.
2. Modify the `run` function so it only executes `initialize_storage!`.
