### ISSUE TITLE
Allow PostgreSQL port number to be defined in config

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/eventstore#43]
Extend `eventstore` config to include `port` setting:

```elixir
config :eventstore, EventStore.Storage,
  username: "postgres",
  password: "postgres",
  database: "eventstore_dev",
  hostname: "localhost",
  port: 5432,
  pool_size: 10
```

**Comment by paulewetzel** [comment]
Is this an old issue that was fixed and never cleared? I am able to create and drop the db with or without a port config entry. It also fails if I add the wrong port.

**Comment by slashdotdash** [comment]
Yes, looks like it's already fixed. Thanks.
