### ISSUE TITLE
Support `events.causation_id`

### ISSUE THREAD

**Issue by harukizaemon** [slashdotdash/eventstore#45]
In addition to `correlation_id` for tracing a thread of execution, in a number of production systems we've found it helpful to also have a `causation_id` being the ID of the message that directly triggered the creation of the events.

To implement, this is usually a matter of not only copying the `correlation_id` from the inbound message but also populating the `causation_id` from the ID of the message itself.

**Comment by slashdotdash** [comment]
I'll add this to the backlog. For now, you could include the additional `causation_id` property in the event metadata.

**Comment by slashdotdash** [comment]
Done by @harukizaemon in #48.
