### ISSUE TITLE
Support UUIDs for `stream_id`

### ISSUE THREAD

**Issue by harukizaemon** [slashdotdash/eventstore#46]
It's fairly commonplace to use a UUID as a stream identifier. Is there any chance that could be supported?

**Comment by slashdotdash** [comment]
Appending events to a stream already uses a string to uniquely identify the stream. 

`stream_uuid` is of type string in the `EventStore.append_to_stream` function:

```elixir
@spec append_to_stream(String.t, non_neg_integer, list(EventData.t)) :: :ok | {:error, reason :: term}
def append_to_stream(stream_uuid, expected_version, events)
```

**Comment by harukizaemon** [comment]
Ahh sorry. That'll teach me to write stuff up on my phone over the break -- totally my bad. I didn't see that! Would you be open to changing it to a native postgresql UUID column and convert from using String.t to e.g. https://hex.pm/packages/uuid? given that would break the API I'm guessing no.

**Comment by slashdotdash** [comment]
I use the `uuid` library to generate the stream UUIDs as it creates strings. No changes required.

```iex
iex> UUID.uuid4()
"fcfe5f21-8a08-4c9a-9f97-29d2fd6a27b9"
```

**Comment by harukizaemon** [comment]
Ahh! I didn't realise it generated strings. Right. So then really it's just down to whether or not the column itself could be made a native PostgreSQL UUID or if your intent there was that whilst UUIDs make sense in many case, people ought to be free to use whatever identifiers they want? (As an aside, PostgreSQL stores UUID typed columns natively in a more compact format).
