### ISSUE TITLE
Setting custom metadata on events

### ISSUE THREAD

**Issue by davich** [slashdotdash/eventstore#52]
I'm using Eventstore with Commanded. I want to be able to set custom metadata on an event (the user who created it, etc). Is there anyway to do this?

I've had a bit of a look and it looks like Aggregate.persist_events doesn't pass in any metadata to Mapper.map_to_event_data. 

Thanks

**Comment by slashdotdash** [comment]
Sorry for the late response @davich. You can append metadata with an event to the event store, but it's not currently supported in Commanded. 

It's certainly a worthwhile feature to add. So I've opened an issue against the Commanded project for this ([#61](https://github.com/slashdotdash/commanded/issues/61)).

**Comment by DominikGuzei** [comment]
Yeah i would also like to know the best way to save metadata to events … @slashdotdash how are you doing it in your apps, just putting it onto the events directly?
