### ISSUE TITLE
Writer per event stream

### ISSUE THREAD

**Issue by slashdotdash** [slashdotdash/eventstore#55]
Currently Event Store uses a single writer process ([EventStore.Writer](https://github.com/slashdotdash/eventstore/blob/cb83101db3c6c4f60c475f24a79115a61bb1b57b/lib/event_store/writer.ex)) to append events to PostgreSQL. The writer assigns the monotonically incrementing event id during insert.

To support running on a cluster of nodes (#53), we need to support multiple writers, distributed amongst the cluster: one writer per event stream. 

This means that event id generation must also move to PostgreSQL. It's possible to use a function to assign a value in PostgreSQL (e.g. `event_id`) from a value in another table during insert. This is to achieve *gapless* event ids (which are not guaranteed when using a sequence).

- [Gapless Sequences for Primary Keys](http://www.varlena.com/GeneralBits/130.php)
- [Gapless sequence without locking the whole table](http://mssql-to-postgresql.blogspot.co.uk/2007/12/gapless-sequence-without-locking-whole.html?m=1)

In addition, the subscription pub/sub will need to be reworked to support multiple publishers (writers). Persisted events will need to be sent to subscribers ordered by `event_id`, but may be received by the publisher out of order.

--- 

## Single writer process (current implementation)

Single `EventStore.Writer`  process to:

1. Assign the incrementing event id.
2. Append events to PostgreSQL database.
3. Publish events to subscriptions.

![single_writer_process](https://user-images.githubusercontent.com/3167/28997820-cd88a34c-7a15-11e7-89bf-3d0de69317df.png)

## Multiple writer processes (proposal)

Each `EventStore.Streams.Stream` process will append its events to PostgreSQL database. The event id will be assigned by the database. Published events will be sent to subscribers sorted by event id. This will require a pending event buffer as events may be received by the subscriptions process out of order due to multiple writer processes.

![multiple_writer_processes](https://user-images.githubusercontent.com/3167/28997819-cd885694-7a15-11e7-813e-5bbf585913f9.png)

**Comment by benwilson512** [comment]
Hey! Can you elaborate on the need to use a writer process at all? Can't postgres transactions be used to get the atomicity properties you want? Also i'm curious about the gapless requirements, why is that necessary?

**Comment by slashdotdash** [comment]
The EventStore has been designed to append events to PostgreSQL using a single writer process so that it can: assign a globally ordered, monotonically incrementing, event identifier; serialise event writing to ease pub/sub notifications to event handlers; and allow handlers to store their last seen event id as a pointer to resume on restart. The benefits of a linear event store are [outlined in this article](http://squirrel.pl/blog/2015/09/14/achieving-consistency-in-cqrs-with-linear-event-store/). 

This approach requires a gapless event id for the following reason: when an event handler receives events 1,2,3,4 it know the next event must be 5. If it receives <5 (due to at least once delivery) it can ignore the event. If it receives 5 then all is good, but anything >5 indicates the handler has missed an event. It should take remedial action (restart from last seen event + 1). So it's a safety measure and sanity check. 

Switching to multiple writers, one per node or stream, means PosthreSQL will need to assign the event id. Using the gapless sequence functions I've linked above. It also means that the pun/sub to event handlers will need to buffer events received from the multiple writers to publish them ordered by their id. This is necessary as the notification of appended events from multiple writers might not occur in the same order as they were persisted.

Hope that clarifies some of the design decisions. Using a global event order makes it significantly easier for the developer as they can safely assume events will be causally ordered. The drawback is needing to funnel writes sequentially to one process. Have a look at the LMAX architecture for a very high performance implementation, using a ring buffer, of a single threaded writer process.

**Comment by slashdotdash** [comment]
Fixed by #59.
