### ISSUE TITLE
Example Serializer using Poison does not work

### ISSUE THREAD

**Issue by mbaeuerle** [slashdotdash/eventstore#61]
When using the [example serializer](https://github.com/slashdotdash/eventstore#event-serialization) shown in the readme I get an error when it's trying to deserialize the Event:
```elixir
** (UndefinedFunctionError) function :ExampleEvent.__struct__/0 
is undefined (module :ExampleEvent is not available)
```

I think there is a problem with this code:
```elixir
  type -> type |> String.to_existing_atom |> struct
```

`type` is a string containing `ExampleEvent` which is converted to an atom `:ExampleEvent`
But the `struct\2` function can't convert Atoms to Structs. Or am I getting something wrong?

**Comment by Papipo** [comment]
Have you defined an ExampleEvent struct?

**Comment by mbaeuerle** [comment]
Sure: 
```elixir
defmodule ExampleEvent do
  defstruct [:key]
end
```
But `struct(:ExampleEvent)` throws the error, only `struct(ExampleEvent)` does work

**Comment by slashdotdash** [comment]
@mbaeuerle The type should be converted to a string as `Elixir.ExampleEvent`.

```
iex> String.to_existing_atom("Elixir.ExampleEvent")
ExampleEvent
```

**Comment by slashdotdash** [comment]
I will update the README to include the above information to assist future users.

**Comment by mbaeuerle** [comment]
Ah I see, it's using
```elixir
struct(:"Elixir.ExampleEvent")
```

Thanks!
